name: main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  env:
    uses: devxp-tech/.github/.github/workflows/env.yml@main

  test:
    uses: devxp-tech/.github/.github/workflows/test-golang.yml@main

  quality-gate:
    uses: devxp-tech/.github/.github/workflows/sonarqube.yml@main
    secrets:
      SONARQUBE_HOST: ${{ secrets.SONARQUBE_HOST }}
      SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}

  # Test
  # synk:
  #   uses: devxp-tech/.github/.github/workflows/synk-golang.yml@main
  #   needs:
  #     - env
  #   secrets:
  #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build-and-push:
    uses: devxp-tech/.github/.github/workflows/build-and-push.yml@main
    with:
      tag: ${{ needs.env.outputs.tag }}
    needs:
      - env
      - test
      - quality-gate

  trivy:
    uses: devxp-tech/.github/.github/workflows/trivy.yml@main
    needs:
      - build-and-push

  deploy:
    uses: devxp-tech/.github/.github/workflows/deploy.yml@main
    with:
      tag: ${{ needs.env.outputs.tag }}
      repository: ${{ needs.env.outputs.repository }}
    needs:
      - env
      - trivy

  notify:
    uses: devxp-tech/.github/.github/workflows/notify.yml@main
    if: always()
    with:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    needs:
      - env
      - test
      - quality-gate
      # - synk
      - build-and-push
      - trivy
      - deploy
