name: main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  env:
    uses: devxp-tech/.github/.github/workflows/env.yml@main

  test:
    uses: devxp-tech/.github/.github/workflows/test-golang.yml@main

  sonarqube:
    uses: devxp-tech/.github/.github/workflows/sonarqube.yml@main
    secrets:
      SONARQUBE_HOST: ${{ secrets.SONARQUBE_HOST }}
      SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}

  # synk:
  #   uses: devxp-tech/.github/.github/workflows/synk-golang.yml@main
  #   needs:
  #     - env
  #   secrets:
  #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build-and-push:
    uses: devxp-tech/.github/.github/workflows/build-and-push.yml@main
    with:
      tag: ${{ needs.env.outputs.tag }}
    needs:
      - env
      - test
      - sonarqube

  trivy:
    uses: devxp-tech/.github/.github/workflows/trivy.yml@main
    needs:
      - build-and-push

  deploy:
    uses: devxp-tech/.github/.github/workflows/deploy.yml@main
    with:
      tag: ${{ needs.env.outputs.tag }}
    needs:
      - env
      - trivy

  slack-workflow-status:
    if: always()
    name: Post Status To Slack  ðŸ“£
    needs:
      # - env
      # - test
      # - sonarqube
      # - synk
      # - build-and-push
      # - trivy
      - deploy
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          # Required Input
          repo_token: ${{secrets.ACCESS_TOKEN_GITHUB}}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          # Optional Input
          channel: 'github-notifications'
          name: 'github-notifications'
          # icon_emoji: ':poop:'
          icon_url: ${{ secrets.SLACK_ICON }}

